<!DOCTYPE html><html><div class="item-title">
        Item 279
      </div> <div class="item-details"><div><b>git_comments:</b> <ol></ol></div><div><b>git_commits:</b> <ol><li><div><div><b>summary:</b> PHOENIX-2313 TypeMismatchException thrown while querying a table that has an index with a Boolean(Rajeshbabu)
                </div><div><b>message:</b> PHOENIX-2313 TypeMismatchException thrown while querying a table that has an index with a Boolean(Rajeshbabu)

                </div></div></li></ol></div><div><b>github_issues:</b> <ol></ol></div><div><b>github_issues_comments:</b> <ol></ol></div><div><b>github_pulls:</b> <ol></ol></div><div><b>github_pulls_comments:</b> <ol></ol></div><div><b>github_pulls_reviews:</b> <ol></ol></div><div><b>jira_issues:</b> <ol><li><div><div><b>summary:</b> TypeMismatchException thrown while querying a table that has an index with a Boolean
                </div><div><b>description:</b> Getting below exception scanning through index on boolean column.
{noformat}
java.lang.RuntimeException: org.apache.phoenix.schema.TypeMismatchException: ERROR 203 (22005): Type mismatch. DECIMAL cannot be coerced to BOOLEAN 
at sqlline.SqlLine$IncrementalRows.hasNext(SqlLine.java:2440) 
at sqlline.SqlLine$TableOutputFormat.print(SqlLine.java:2074) 
at sqlline.SqlLine.print(SqlLine.java:1735) 
at sqlline.SqlLine$Commands.execute(SqlLine.java:3683) 
at sqlline.SqlLine$Commands.sql(SqlLine.java:3584) 
at sqlline.SqlLine.dispatch(SqlLine.java:821) 
at sqlline.SqlLine.begin(SqlLine.java:699) 
at sqlline.SqlLine.mainWithInputRedirection(SqlLine.java:441) 
at sqlline.SqlLine.main(SqlLine.java:424) 
{noformat}
Here are simple steps to reproduce
{noformat}
CREATE TABLE TABLE_TEST (PK INTEGER PRIMARY KEY, COL1 BOOLEAN);
UPSERT INTO TABLE_TEST VALUES (1, true);
UPSERT INTO TABLE_TEST VALUES (2, false);
SELECT * FROM TABLE_TEST;
CREATE INDEX TABLE_TEST_IDX ON TABLE_TEST(COL1);
SELECT * FROM TABLE_TEST;
DROP TABLE TABLE_TEST;
{noformat}
                </div></div></li></ol></div><div><b>jira_issues_comments:</b> <ol><li><div>
                Here is the patch fixes it.
              </div></li><li><div>
                +1 Looks good. 

              </div></li><li><div>
                Pushed to master and 4.x branches. Thanks for review [~aliciashu].
              </div></li><li><div>
                FAILURE: Integrated in Phoenix-master #928 (See [https://builds.apache.org/job/Phoenix-master/928/])
PHOENIX-2313 TypeMismatchException thrown while querying a table that (rajeshbabu: rev f02fb1b06e55b6d870a42ec051d3fbf18bb39e01)
* phoenix-core/src/it/java/org/apache/phoenix/end2end/index/BaseMutableIndexIT.java
* phoenix-core/src/main/java/org/apache/phoenix/schema/types/PBoolean.java

              </div></li><li><div>
                It seems like this change is breaking the following tests in 1.0 and master:

{code}
Tests run: 53, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 471.903 sec &lt;&lt;&lt; FAILURE! - in org.apache.phoenix.end2end.AlterTableIT
testDropIndexedColumn(org.apache.phoenix.end2end.AlterTableIT)  Time elapsed: 8.293 sec  &lt;&lt;&lt; ERROR!
java.sql.SQLException: ERROR 2009 (INT11): Unknown error code 0
	at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:398)
	at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:145)
	at org.apache.phoenix.exception.SQLExceptionCode.fromErrorCode(SQLExceptionCode.java:426)
	at org.apache.phoenix.util.ServerUtil.parseRemoteException(ServerUtil.java:127)
	at org.apache.phoenix.util.ServerUtil.parseServerExceptionOrNull(ServerUtil.java:115)
	at org.apache.phoenix.util.ServerUtil.parseServerException(ServerUtil.java:104)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.metaDataCoprocessorExec(ConnectionQueryServicesImpl.java:1053)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.metaDataCoprocessorExec(ConnectionQueryServicesImpl.java:1016)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.dropColumn(ConnectionQueryServicesImpl.java:1819)
	at org.apache.phoenix.schema.MetaDataClient.dropColumn(MetaDataClient.java:2880)
	at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableDropColumnStatement$1.execute(PhoenixStatement.java:1147)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:322)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:314)
	at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:312)
	at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1435)
	at org.apache.phoenix.end2end.AlterTableIT.testDropIndexedColumn(AlterTableIT.java:285)

testDropCoveredColumn(org.apache.phoenix.end2end.AlterTableIT)  Time elapsed: 8.428 sec  &lt;&lt;&lt; ERROR!
java.sql.SQLException: ERROR 2009 (INT11): Unknown error code 0
	at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:398)
	at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:145)
	at org.apache.phoenix.exception.SQLExceptionCode.fromErrorCode(SQLExceptionCode.java:426)
	at org.apache.phoenix.util.ServerUtil.parseRemoteException(ServerUtil.java:127)
	at org.apache.phoenix.util.ServerUtil.parseServerExceptionOrNull(ServerUtil.java:115)
	at org.apache.phoenix.util.ServerUtil.parseServerException(ServerUtil.java:104)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.metaDataCoprocessorExec(ConnectionQueryServicesImpl.java:1053)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.metaDataCoprocessorExec(ConnectionQueryServicesImpl.java:1016)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.dropColumn(ConnectionQueryServicesImpl.java:1819)
	at org.apache.phoenix.schema.MetaDataClient.dropColumn(MetaDataClient.java:2880)
	at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableDropColumnStatement$1.execute(PhoenixStatement.java:1147)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:322)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:314)
	at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:312)
	at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1435)
	at org.apache.phoenix.end2end.AlterTableIT.testDropCoveredColumn(AlterTableIT.java:350)

testDropColumnsWithImutability(org.apache.phoenix.end2end.AlterTableIT)  Time elapsed: 14.768 sec  &lt;&lt;&lt; ERROR!
java.sql.SQLException: ERROR 2009 (INT11): Unknown error code 0
	at org.apache.phoenix.exception.SQLExceptionCode$Factory$1.newException(SQLExceptionCode.java:398)
	at org.apache.phoenix.exception.SQLExceptionInfo.buildException(SQLExceptionInfo.java:145)
	at org.apache.phoenix.exception.SQLExceptionCode.fromErrorCode(SQLExceptionCode.java:426)
	at org.apache.phoenix.util.ServerUtil.parseRemoteException(ServerUtil.java:127)
	at org.apache.phoenix.util.ServerUtil.parseServerExceptionOrNull(ServerUtil.java:115)
	at org.apache.phoenix.util.ServerUtil.parseServerException(ServerUtil.java:104)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.metaDataCoprocessorExec(ConnectionQueryServicesImpl.java:1053)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.metaDataCoprocessorExec(ConnectionQueryServicesImpl.java:1016)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.dropColumn(ConnectionQueryServicesImpl.java:1819)
	at org.apache.phoenix.schema.MetaDataClient.dropColumn(MetaDataClient.java:2880)
	at org.apache.phoenix.jdbc.PhoenixStatement$ExecutableDropColumnStatement$1.execute(PhoenixStatement.java:1147)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:322)
	at org.apache.phoenix.jdbc.PhoenixStatement$2.call(PhoenixStatement.java:314)
	at org.apache.phoenix.call.CallRunner.run(CallRunner.java:53)
	at org.apache.phoenix.jdbc.PhoenixStatement.executeMutation(PhoenixStatement.java:312)
	at org.apache.phoenix.jdbc.PhoenixStatement.execute(PhoenixStatement.java:1435)
	at org.apache.phoenix.end2end.AlterTableIT.testDropColumnsWithImutability(AlterTableIT.java:874)
{code}
              </div></li><li><div>
                Addendum patch with more lower level unit tests. When an index was used, it wasn't interpreting the value correctly. I'm not sure if this is going to fix the test failures as I'm unable to reproduce them. However, the boolean value when indexed is interpreted correctly now.
              </div></li><li><div><div><b>body:</b> [~jamestaylor]
+1 on addendum. The test failures are flaky before this patch commit as well.
https://builds.apache.org/view/All/job/Phoenix-4.x-HBase-1.0/190/testReport/
                </div><div><b>label:</b> test
                </div></div></li><li><div>
                FAILURE: Integrated in Phoenix-master #931 (See [https://builds.apache.org/job/Phoenix-master/931/])
PHOENIX-2313 TypeMismatchException thrown while querying a table that (jtaylor: rev 7bc93f405be9f5700f12682e0e505820a0581f84)
* phoenix-core/src/main/java/org/apache/phoenix/schema/types/PBoolean.java
* phoenix-core/src/it/java/org/apache/phoenix/end2end/index/BaseMutableIndexIT.java
* phoenix-core/src/test/java/org/apache/phoenix/schema/types/PDataTypeTest.java

              </div></li><li><div>
                Bulk close of all issues that has been resolved in a released version. 
              </div></li></ol></div></div></html>